### ISSUE TITLE
Custom spawns effecting players outside permissions group

### ISSUE THREAD

**Issue by itsTEOTWAWKI** [sharkbound/CustomSpawnpoints#1]
In testing out this plugin, I created a custom spawn and assigned it to a permissions group so that only the people in that group would be able to utilize the spawn point, but the spawn ended up in the regular rotation as well.

Do I need to create custom spawns for all permissions groups to prevent custom spawns assigned to a specific permissions group (via the spawn.spawnname permission) from effecting players outside the intended group?

**Comment by sharkbound** [comment]
what permissions does the default group have?

**Comment by itsTEOTWAWKI** [comment]
Default group had no permissions set for this plugin.  The custom spawn point was only referenced in the permissions for the permissions group it was intended for.

**Comment by sharkbound** [comment]
try the latest download on the plugins rocketmod page, i think i fixed it.

**Comment by itsTEOTWAWKI** [comment]
Seems to be functioning as intended now, thank you!
