### ISSUE TITLE
i sent a message on the plugin repository on rocketmod.net!

### ISSUE THREAD

**Issue by Avril112113** [sharkbound/CustomSpawnpoints#2]
Please Read What I Said Other There
https://dev.rocketmod.net/plugins/customspawnpoints

**Comment by sharkbound** [comment]
Just for context:
![Context](https://i.gyazo.com/f5dbd76e7bd21bd1861640f0b18b4bcb.png)

**Comment by sharkbound** [comment]
also, what is your permissions file && the plugins config look like?

**Comment by Avril112113** [comment]
Plugin Config:
https://pastebin.com/f2vfenZc

Permission: (the 3 that are involved)
https://pastebin.com/xwqmX7Uq
KEEP IN MIND ITS NOT THE WHOLE FILE AS I WANT TO KEEP THAT PRIVATE

It just says no permission to the command (/spawn spawn), the only time anyone can use the commands is when thay have the permission "spawn" but that give all perms to all stuff so

**Comment by sharkbound** [comment]
the ```spawnpoint.foo``` permissions gives them permission to be able to be respawned there, and the /spawn command is a admin command meant for managing spawns. 
I am working on adding individual permissions for the /spawn command so you can limit / only give permission to tp'ing to spawn

**Comment by Avril112113** [comment]
So how can I let players teleport to a location I set?
Or is that just not a thing at the moment?

**Comment by sharkbound** [comment]
What you are discribing is a warp plugin, there is a warp plugin on the repo, and uessentials also adds warps i think

**Comment by Avril112113** [comment]
I used a warp plugin insted. But I didnt under stand how your plugin worked until you told me so, a better desc on plugin or something like that will be nice, but anyway thanks
